import { Task, TaskList } from './types';
import { v4 as uuidv4 } from 'uuid';

export const seedLists: TaskList[] = [
  {
    id: 'list-pessoal',
    name: 'Pessoal',
    color: '#10b981',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'list-trabalho',
    name: 'Trabalho',
    color: '#3b82f6',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'list-estudos',
    name: 'Estudos',
    color: '#8b5cf6',
    createdAt: new Date('2024-01-01'),
  },
];

export const seedTasks: Task[] = [
  {
    id: uuidv4(),
    title: 'Revisar relatório mensal',
    description: 'Revisar e finalizar o relatório de vendas do mês passado',
    priority: 'alta',
    status: 'pendente',
    listId: 'list-trabalho',
    tags: ['financeiro', 'urgente'],
    dueDate: new Date(Date.now() - 24 * 60 * 60 * 1000), // Ontem (vencida)
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    subtasks: [
      { id: uuidv4(), title: 'Coletar dados de vendas', completed: true },
      { id: uuidv4(), title: 'Analisar tendências', completed: false },
      { id: uuidv4(), title: 'Criar gráficos', completed: false },
    ],
    photos: [],
  },
  {
    id: uuidv4(),
    title: 'Consulta médica',
    description: 'Checkup anual com cardiologista',
    priority: 'media',
    status: 'pendente',
    listId: 'list-pessoal',
    tags: ['saúde'],
    dueDate: new Date(), // Hoje
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
    subtasks: [],
    photos: [],
  },
  {
    id: uuidv4(),
    title: 'Apresentação do projeto X',
    description: 'Preparar slides para apresentação do novo projeto para a diretoria',
    priority: 'urgente',
    status: 'pendente',
    listId: 'list-trabalho',
    tags: ['projeto-x', 'apresentação'],
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000), // Em 2 dias
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
    subtasks: [
      { id: uuidv4(), title: 'Criar outline', completed: true },
      { id: uuidv4(), title: 'Desenvolver slides', completed: false },
      { id: uuidv4(), title: 'Praticar apresentação', completed: false },
    ],
    photos: [],
  },
  {
    id: uuidv4(),
    title: 'Estudar React Hooks',
    description: 'Aprofundar conhecimentos em useEffect e useCallback',
    priority: 'media',
    status: 'concluida',
    listId: 'list-estudos',
    tags: ['react', 'javascript'],
    dueDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000), // Semana passada
    completedAt: new Date('2024-01-18'),
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-18'),
    subtasks: [],
    link: 'https://react.dev/reference/react/hooks',
    photos: [],
  },
  {
    id: uuidv4(),
    title: 'Comprar ingredientes para jantar',
    description: 'Lista de compras para o jantar de amanhã',
    priority: 'baixa',
    status: 'pendente',
    listId: 'list-pessoal',
    tags: ['compras', 'casa'],
    dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000), // Amanhã
    createdAt: new Date(),
    updatedAt: new Date(),
    subtasks: [
      { id: uuidv4(), title: 'Salmão', completed: false },
      { id: uuidv4(), title: 'Aspargos', completed: false },
      { id: uuidv4(), title: 'Vinho branco', completed: false },
    ],
    photos: [],
  },
  {
    id: uuidv4(),
    title: 'Implementar testes unitários',
    description: 'Criar testes para os novos componentes do sistema',
    priority: 'alta',
    status: 'pendente',
    listId: 'list-trabalho',
    tags: ['testes', 'desenvolvimento'],
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000), // Em 5 dias
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
    subtasks: [],
    photos: [],
  },
  {
    id: uuidv4(),
    title: 'Ler livro sobre produtividade',
    description: 'Atomic Habits - James Clear',
    priority: 'baixa',
    status: 'pendente',
    listId: 'list-pessoal',
    tags: ['leitura', 'desenvolvimento-pessoal'],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
    subtasks: [],
    photos: [],
  },
  {
    id: uuidv4(),
    title: 'Reunião de alinhamento',
    description: 'Sync semanal com o time de desenvolvimento',
    priority: 'media',
    status: 'concluida',
    listId: 'list-trabalho',
    tags: ['reunião', 'equipe'],
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 dias atrás
    completedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-16'),
    subtasks: [],
    photos: [],
  },
  {
    id: uuidv4(),
    title: 'Curso TypeScript Avançado',
    description: 'Módulo 3: Utility Types e Conditional Types',
    priority: 'media',
    status: 'pendente',
    listId: 'list-estudos',
    tags: ['typescript', 'programação'],
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), // Em 3 dias
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-11'),
    subtasks: [
      { id: uuidv4(), title: 'Assistir vídeo aula', completed: true },
      { id: uuidv4(), title: 'Fazer exercícios práticos', completed: false },
      { id: uuidv4(), title: 'Criar projeto exemplo', completed: false },
    ],
    photos: [],
  },
  {
    id: uuidv4(),
    title: 'Organizar escritório em casa',
    description: 'Reorganizar mesa de trabalho e arquivos',
    priority: 'baixa',
    status: 'pendente',
    listId: 'list-pessoal',
    tags: ['organização', 'casa'],
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-13'),
    subtasks: [],
    photos: [],
  },
  {
    id: uuidv4(),
    title: 'Refatorar componente de login',
    description: 'Melhorar performance e adicionar validação',
    priority: 'media',
    status: 'pendente',
    listId: 'list-trabalho',
    tags: ['refactor', 'frontend'],
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // Em 1 semana
    createdAt: new Date('2024-01-17'),
    updatedAt: new Date('2024-01-17'),
    subtasks: [],
    photos: [],
  },
  {
    id: uuidv4(),
    title: 'Praticar violão',
    description: 'Estudar nova música: Hotel California',
    priority: 'baixa',
    status: 'concluida',
    listId: 'list-pessoal',
    tags: ['música', 'hobby'],
    completedAt: new Date(),
    createdAt: new Date('2024-01-19'),
    updatedAt: new Date(),
    subtasks: [],
    photos: [],
  },
];