// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bobrqioydwrjgetyqdmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvYnJxaW95ZHdyamdldHlxZG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5OTI0MjksImV4cCI6MjA3MTU2ODQyOX0.Bzq-0nknDR5JGQhGIe7BthQXf0lbfMxMDsAMZDdNtT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});